sudo: required
services:
  - docker

before_install:
  - docker build -t rogerbu/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run rogerbu/react-test npm test -- --coverage

after_success:
  - docker build -t rogerbu/multi-client ./client
  - docker build -t rogerbu/multi-nginx ./nginx
  - docker build -t rogerbu/multi-server ./server
  - docker build -t rogerbu/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rogerbu/multi-client
  - docker push rogerbu/multi-nginx 
  - docker push rogerbu/multi-server 
  - docker push rogerbu/multi-worker 
  