version: '3'
services:
  postgres:
    image: 'postgres:10'
  redis:
    image: 'redis:5'
  nginx:
    restart: always
    build: 
      dockerfile: dev.Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: dev.Dockerfile
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  work:
    build:
      dockerfile: dev.Dockerfile
      context: ./worker
    volumes: 
      - /app/node_modules
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
